<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Compile Include="Entities.fs"/>
        <Compile Include="Mapping.fs"/>
        <Compile Include="Respositories.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.UMX"/>
        <PackageReference Include="MongoDB.Driver"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\osaHealth.Domain\osaHealth.Domain.fsproj"/>
    </ItemGroup>

</Project>
