<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Compile Include="Entities.fs"/>
        <Compile Include="Mapping.fs"/>
        <Compile Include="Respositories.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.UMX" Version="1.1.0"/>
        <PackageReference Include="MongoDB.Driver" Version="3.9.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\osaHealth.Domain\osaHealth.Domain.fsproj"/>
    </ItemGroup>

</Project>
