apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
    version: 1
    editable: false

  - name: Zipkin
    type: zipkin
    uid: zipkin
    url: http://zipkin:9411
    access: proxy
    isDefault: false
    version: 1
    editable: false
