apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
auth:
  secretStore: vault-secret-store
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: "mongodb:27017"
    - name: username
      secretKeyRef:
        name: mongodb
        key: username
    - name: password
      secretKeyRef:
        name: mongodb
        key: password
    - name: databaseName
      value: "osahealth"
    - name: params
      value: "?authSource=admin"
    - name: writeConcern
      value: "majority"
    - name: readConcern
      value: "majority"
    - name: queryIndexes
      value: '[{"index":{"value.userId":1,"value.recordedAt":1},"name":"userId_recordedAt"}]'
