apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault-secret-store
auth:
  secretStore: local-secret-store
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://vault:8200"
    - name: vaultToken
      secretKeyRef:
        name: vaultToken
    - name: vaultKVUsePrefix
      value: "false"
