<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Compile Include="AssemblyInfo.fs"/>
        <Compile Include="MongoFixture.fs"/>
        <Compile Include="TestHost.fs"/>
        <Compile Include="ListRecordingsSteps.fs"/>
        <Compile Include="ListRecordingsFeature.Tests.fs"/>
        <Compile Include="Tests.fs"/>
        <None Include="xunit.runner.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers.MongoDb"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Update="FSharp.Core"/>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\osaHealth.Api\osaHealth.Api.fsproj"/>
        <ProjectReference Include="..\osaHealth.Framework.Xunit\osaHealth.Framework.Xunit.fsproj"/>
    </ItemGroup>

</Project>