<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Compile Include="Measures.fs" />
        <Compile Include="ErrorHandling.fs" />
        <Compile Include="Entities.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    </ItemGroup>

</Project>
