<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Library.fs"/>
        <Compile Include="Json.fs" />
        <Compile Include="StringUtil.fs" />
        <Compile Include="DateTime.fs" />
        <Compile Include="Guid.fs" />
        <Compile Include="Api.fs" />
        <Compile Include="Dapr.fs" />
        <Compile Include="Testing\Bdd.fs" />
    </ItemGroup>
</Project>
