apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: "repl-mongo:27017"
    - name: databaseName
      value: "osahealth"
    - name: collectionName
      value: "recordings"
    - name: writeConcern
      value: "majority"
    - name: readConcern
      value: "majority"
